source 'https://rubygems.org'
ruby '2.7.2'

gem 'sinatra'
gem 'sinatra-flash'
gem 'sinatra-contrib'
gem 'shotgun'
gem 'zurb-foundation'
gem 'compass'
gem 'rake'
gem 'pony'
gem 'faker'
gem 'uuid'
gem 'mimemagic', '~> 0.4.3'
gem 'activesupport', '~> 5.0.0.1'
group :test do
  gem 'selenium-webdriver', '~> 3.4.0'
  gem 'rspec', '~> 3.5.0'
  gem 'sauce_whisk', '~> 0.1.0'
end
